### PR TITLE
fix typos in software-other.md

### PR DESCRIPTION
**Pull request by Thomas-Moore-Creative**
fix typos (and GitNoob testing PR to patched branch from fork)

### CODE REVIEW

**Review by hot007 — COMMENTED** [review]
These changes look good to me - I have no idea how patching branches works either so just adding my review for fun!

**Comment by Thomas-Moore-Creative** [comment]
I'm going to merge this trivial PR which *should* make changes to @paolap 's [ACDguide:restructure_paola](https://github.com/ACDguide/BigData/tree/restructure_paola) branch?

**Comment by paolap** [comment]
go for it, I might have fixed one typo myself in the meantime and added a bit more content, but that should make the experiment more interesting

**Comment by Thomas-Moore-Creative** [comment]
[ confused face ] I think I've pulled down the patched branch and built the book but I'm confused as it seems the file naming structure had / has changed and I'm not clear if my trivial typo changes are there as I now see that content locally in a different file name `file:///......./code/BigData/BigData/_build/html/tools/tools-other.html`

**Comment by paolap** [comment]
Just clean up your build completely "rm -rf  _build" and build again.
I changed the names probably after you forked and your changes have been merged with mine, so added to the renamed files. The "tools" files are a relic, they shouldn't show in the new build. The changes should be in the software files.

**Comment by Thomas-Moore-Creative** [comment]
I'm just a huge GitNoob and failed to remember that my local repo is a `fork` of [ACDguide:restructure_paola](https://github.com/ACDguide/BigData/tree/restructure_paola) and (DUH!) I need to sync my fork before pulling down will bring my local copy the changes!! 

Seems like I've advanced to being able to fix typos in a patched branch of a fork.  Changes rendered.

**Pull request merged**
