### PR TITLE
same changes as my last commit - the intention is to be able to create a pull request - fixes #33

### LINKED ISSUE #33: intake issues with opening authorised catalogue resolved!
intake had issues with opening an authorised thredds catalogue. Including the username and password in the URL helped to open the catalogue but passing data to dask generated an error message relating to "nonnumeric port" in the URL. Nikhil from CSIRO Data61 advised me to create a .netrc file and a .dodsrc file in my home directory to resolve the issue. The .netrc file contains details about the machine, username, and password. The .dodsrc file points to the location of the .netrc file. I work on OOD and it wasn't enough to create these files in my NCI home directory, I had to create them in my OOD home directory to resolve the issue.

### PR DESCRIPTION
**Pull request by AliciaTak**
I couldn't create a pull request after my last commit because I didn't have a branch. Now I committed my last changes again in my branch to be able to create a pull request. 
I added some more background information and a hint to the "working with authorised catalogues..." section, please review. Thanks!

### CODE REVIEW

**Comment by hot007** [comment]
Looks good to me. Only comment is under "hint" at the end it should be "method works" not "methods works". 
Fine to merge from my PoV.

**Comment by paigem** [comment]
I have three very minor suggestions:
1. Change the semi-colon after "password" to a period. I think that reads better (I also think I'm the one that suggested the semi-colon in the first place - whoops!)
2. I think it would be clearer to make the entire code lines for both the .netrc and .dodsrc files to be formatted as code. E.g.: `machine <machine_name> login <user_ID> password <password>`. Do the angled brackets need to be included in the line of code? If not, they can indicate the locations where the user needs to add their own input. 
3. I would also format the `.netrc` and `.dodsrc` mentions in the text as code, as I've done here. 

Thanks @AliciaTak - all good to merge other than the small comments from @hot007 and me! :)

**Comment by AliciaTak** [comment]
Hi, 
I fixed the suggested amendments; can I merge, or does it need to be reviewed again? Thanks!

**Comment by paigem** [comment]
Good question @AliciaTak - if you just made the suggested updates then go ahead and merge! 🎉

**Pull request merged**
