### PR TITLE
Add content to format_metadata, different_tools and help

### LINKED ISSUE #15: Issue on page /format_metadata.html
Your issue content here.I'm not sure who has been working on this page.
I found an issue which could be added here under "Time"

I changed the dimensions order for the OISST time series, so that Time would be the fastest varying dimension
Going from
   float sst(time, lat, lon)
to
   float sst(lat, lon, time)
The files are ok with ncdump, xarray, NCO, but CDO produces an error:

```
Warning (cdfScanVarAttr): Time must be the first dimension! Unsupported array structure, skipped variable sst!
Warning (cdf_set_var): Inconsistent variable definition for sst!
Warning (cdfInqContents): No data arrays found!
cdo    sinfo: Open failed on >oisst_timeseries_1981.nc<
              Unsupported file structure
```

Files to check this are in /g/data/ua8/NOAA_OISST/AVHRR/timeseries_test/

### LINKED ISSUE #16: Issue on page /format_metadata.html
This is also something we should cover here:

Datasets that can't be opened in xarray without a work around but are common/legitimate
https://github.com/pydata/xarray/issues/2368

### LINKED ISSUE #23: Claire to review format_metadata and other pages
Opening an issue awaiting me to make a pull request to review and add content to the book on other pages.

### PR DESCRIPTION
**Pull request by hot007**
resolves #15 , resolves #16 , resolves #23 

Addresses #24 

Please review! 
Need to check if anchor links work in different_tools page, too.

Thank you :)

### CODE REVIEW

**Comment by paolap** [comment]
I also made quite a lot of changes to different tools trying to test a different formatting and a lot more content but I haven't pushed them yet, so I might try to merge your branch locally with mine, it might take sometime though

**Comment by hot007** [comment]
Ah, sorry Paola :( Please feel free to override my changes where needed - or if it's not too disparate then you could accept this then merge. I suspect I've just caused you a pile of pain though, sorry I should have done it as multiple pull requests in hindsight :(
Also see new comment on #24 which you may have already addressed in your changes.

**Comment by hot007** [comment]
In hindsight we should definitely do one pull request per page!

**Review by chloemackallah — APPROVED** [review]
Love the braindump in format_metadata

**Comment by hot007** [comment]
I'm bad at maths - there's an error in format metadata where I estimate chunk size, it'll be out by a factor of 8 because I forgot that bits and bytes aren't the same thing :p so @chloemackallah that'll need to be fixed. I can do that on review but I'm not going to make any more edits until Paola's had a chance to deal with the mess I made her in the tools section.

**Comment by hot007** [comment]
Then realised I can change that file without affecting @paolap so I've fixed that chunk size estimate. Thanks heaps for the review Chloe! :)

**Comment by hot007** [comment]
DO NOT MERGE THIS PULL REQUEST!!! 
It should not have gone to `main` branch. This PR is replaced by #27 
Instead we should issue a PR to a branch on this repo and then merge branches.

**Comment by hot007** [comment]
I think I can merge this one too now. Apologies for the mess!

**Pull request merged**
