### PR TITLE
Update platforms page building on PR#56

### PR DESCRIPTION
**Pull request by hot007**
Update "platforms" to:
- link each page to index in intro,
- add gadi_jupyter, 
- mention ACCESS-NRI, 
- fix images in OOD page, 
- add an OOD FAQ.

I could not build the book locally (I haven't install jupyterbook) so don't know if this index linking will work, I just followed @paolap 's lead in the "tools" section.

Once merged @paolap  can make further edits.

### CODE REVIEW

**Comment by paolap** [comment]
I've built this on my laptop and the only change needed is the headers' levels.
Jupyter book automatically assign and extra sub-level (`#`) to any headers that appear in any section files .
So for platform (from _toc.yml):
 chapters:
    - file: platforms/platforms-intro
      sections:
      - file: platforms/platforms-nci-gadi
      - file: platforms/platforms-nci-ood
The files under sections currently start with a `##` level, this is interpreted as `###` and causes weird issues, one is that the link don't work.
So you need to `upgrade` all the headers in these files, simply remove a `#` from each header and sub-header.
I can't push to your repo. Apart from that it all looks good.

**Comment by hot007** [comment]
@paigem please advise if you'd like me to fix the header levels on this PR or merge and then pick it up in Paola's PR that will follow once this one's merged. I don't mind either way.

**Comment by paolap** [comment]
same here, I can fix it easily once is merged, but it makes sense to wait for Paige to add her comments first

**Comment by paigem** [comment]
Apologies for the delayed response!

At this point, let's just merge this PR and then fix the headings in a future PR. @hot007 @paolap

**Pull request merged**
