### PR TITLE
Paola toc fix

### PR DESCRIPTION
**Pull request by paolap**
Just a couple of minor fixes to a couple of admonition boxes and an attempt to get the platforms files to show correctly.
For some mysterious reason the filenames for PC, BoM and CSIRO that were changed to lowercase in the last merge, are still uppercase on GitHub, so they aren't shown in the built book

### CODE REVIEW

**Review by hot007 — COMMENTED** [review]
Admonition updates with names are fine.
Not sure what ToC change is being made, I don't see changed file names or ToC file in this PR? Can you please confirm this PR is complete @paolap ?

**Comment by paolap** [comment]
you're right, the files were meant to be named differently in my version, rather than the index, this is what is confusing, it is like if GitHub is not distinguishing between upper and lowercases for the filenames, but jupyter book does, I'll change the index file _toc back to the old names

**Comment by paolap** [comment]
Hopefully this will work, anyway it's the only change plus the admonitions in data/data-netcdf

**Comment by hot007** [comment]
Yep, I had seen that previously, and I thought I'd made the caps consistent but meh, so long as it's fixed! Thanks that looks fine. Will merge now.

**Pull request merged**
