### PR TITLE
Computations introductory page

### PR DESCRIPTION
**Pull request by ScottWales**
Summarising tools and resources for doing computations on large datasets

See #1 

Current state - 
https://github.com/ACDguide/BigData/blob/computations/BigData/computations.ipynb

### CODE REVIEW

**Comment by ScottWales** [comment]
I've added content for the computations page, see the link above for the current view.

In the website the code creating the diagrams will be hidden - these cells are marked with the tag 'hide-input' - you can add tags to a notebook cell in jupyter lab using the gear icon in the top right. https://jupyterbook.org/interactive/hiding.html#hide-cell-inputs

Comments on the format or pointers to resources to add welcome :)

**Comment by Thomas-Moore-Creative** [comment]
who needs Adobe Illustrator when you have `draw_chunks` function.  nice work @ScottWales

**Comment by hot007** [comment]
> I've added content for the computations page, see the link above for the current view.
> 
> In the website the code creating the diagrams will be hidden - these cells are marked with the tag 'hide-input' - you can add tags to a notebook cell in jupyter lab using the gear icon in the top right. https://jupyterbook.org/interactive/hiding.html#hide-cell-inputs
> 
> Comments on the format or pointers to resources to add welcome :)

Hey @ScottWales, I'm interested in this hidden inputs tag - so to do this do you need to develop the content in a jupyterlab not a plain jupyter notebook? Is there any way in the repo to see that these cells are tagged to hide or will it just magically (and mysteriously) happen upon jupyterbook render?
Speaking of which, your computations stuff is in a different branch, how do we select a branch to view at https://acdguide.github.io/BigData/? Is there a way to see it rendered? Sorry massive noob questions!

**Comment by ScottWales** [comment]
Looks like in plain jupyter it's View -> Cell Toolbar -> Tags to edit tags.

I think to see it rendered you'd need to build it locally following the readme instructions or I can put it in the sandbox repository (which I will do) - I don't think github renders pull requests

**Comment by ScottWales** [comment]
Same page in the sandbox https://acdguide.github.io/sandbox/computations.html

**Comment by hot007** [comment]
Awesome, thanks Scott :)

**Pull request merged**
