### PR TITLE
Add paragraph on analysis environments

### LINKED ISSUE #66: Add at least a paragraph on how to access python
Add some discussion on how to use python/conda on Gadi.
-hh5
-dk92?
-don't use your own if there's a shared module/conda you can use.

### PR DESCRIPTION
**Pull request by dougiesquire**
Not sure about the best location for this (see #69). For now, I've just put it somewhere that kinda made sense.

Closes #66

### CODE REVIEW

**Comment by paolap** [comment]
Hi Dougie,

I think where you put it now is not good as that the introduction and we don't usually have much detail in it. Possibly the best place is in the Package and environment section in tools (tools-python1.md file):
https://acdguide.github.io/BigData/tools/tools-python1.html#package-and-environment-management
If you agree I'm happy to have a go at integrating it there.

**Comment by paolap** [comment]
I've moved Dougie addition to tools-python1 as commented above and also reviewed other parts of that file. I'm not sure how to push this without creating havoc. So I might just push it as a separate branch (tools2) so that someone can check it then if the "move" is fine I'll push it to this branch.

**Comment by hot007** [comment]
Okay, I'm pretty confused. I like Dougie's addition (though I'd probably consider explicitly mentioning that the CLEX project containing conda envs is `hh5`), but I haven't suggested edits as @paolap 's comments indicate this PR is not for merging and instead we deal with this elsewhere... so not sure how/where to suggest changes?
I think the edits in the `tools2` branch look okay, but
1) the comment about VSCode can be removed, that looks accurate to me. 
2) I would give a call out to Dougie's added text, e.g. a green rectangle saying "note" if not the whole paragraph? As this is tangible advice rather than general background info like the rest of the page thus far.

Apologies I'm not sure how to action this or who needs to do so... just noting I have read the text and looked at the new branch, just not sure what action I should take.

**Comment by paolap** [comment]
To add to your confusion I ended up moving most of the text to a different part of the book I my restructure and leave in the "tools" section this:

Screen Shot 2022-08-15 at 4 42 53 pm

Because I thought it might make more sense to have this together with other analysis-ready "tools" as centrally managed data collections, pangeo etc. I idd the same for the community list , i.e. removed it from tools/tools-python1.md and added to the analysis-ready file

Screen Shot 2022-08-15 at 4 45 03 pm

If you build my restructure_paola branch is clearer

I guess right now might make more sense to focus on working out a restructure and then we can decide where to put the text, so whichever branch gets merged the additional text is preserved. Thanks for confirming vscode I removed the comment from tools 2 and try to add all that section as a warning, at least a s a temporary fix.

**Pull request merged**
